### ISSUE TITLE
Incompatibility with PyQt5.QtGui

### ISSUE THREAD

**Issue by ptanga** [bob-anderson-ok/pymovie#3]
After a fresh install of version 3.0.1, the "from pymovie import main" command results in the error message:

File "/usr/local/lib/python3.8/site-packages/pymovie/main.py", line 367, in <module>
    class PyMovie(QtGui.QMainWindow, gui.Ui_MainWindow):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMainWindow'
 
which seems to indicate an inconsistency with the required version of the qt library.

Reproduced both under Mac OS and Windows 10.

best regards

**Comment by bob-anderson-ok** [comment]
That is an ominous message. 

Can you give me more information, such as:

1. Has PyMovie ever worked for you?
2. If yes was the answer to the first question, what was the last version that worked?
3. Can you go back to that version?  (pip install pymovie==2.9.8)

Bob

**Comment by ptanga** [comment]
Sorry to have so little additional information, Bob, but here is all that I can say:

- A version 9.2.x worked under windows 10 for a while, then I did not use it for a long time
- I wanted to upgrade, I did a fresh installation to avoid any conflicts, and the error message came
- The error is independent on the platform (Max, Windows, anaconda or not...), and comes probably from the fact that the PyQt5 has a different import declaration for QMainWindow, with respect to previous versions (PyQT4 for instance)
- I removed the last version and downgraded to 9.2.8 and then to 2.9.0 but, during the installation (by pip install), it always checks in the requirement the presence of PyQt5, which is the source of the problem. Due to that, the error message shows up the same for all those versions. 

Unfortunately I cannot say why it worked in the past, the only guess I can make is that for some reasons it used an older version of PyQt, corresponding to the import statement. 

Paolo

**Comment by bob-anderson-ok** [comment]
I have never used anything other than PyQt5 in my programs (PyOTE and PyMovie).

There is no import statement for QMainWindow, but that module is referenced in the code that builds the program window (gui).

I don’t have any suggestions at this time and I have had no other reports of such error messages.

And, normally a fresh install always works and is the recommended practice whenever an installation starts acting ‘funny’.

Bob

**Comment by ptanga** [comment]
My "fresh" install included a full uninstall of anaconda, and a re-install from scratch. I will let you know if I find a way through it...
Paolo

**Comment by bob-anderson-ok** [comment]
Please keep me informed.  I will do what I can to help.

Bob

**Comment by bob-anderson-ok** [comment]
I have uploaded version 3.0.4 of PyMovie. This version solved the problem you are havong for another user - it should work for you.

NOTE: you MUST install this version (this time only) with:

pip install pymovie==3.0.4

Don’t miss the double = characters

Bob

**Comment by ptanga** [comment]
Well done, thank you! It works now. Perfect.
