### ISSUE TITLE
Request for community engagement channels (e.g., Slack)

### ISSUE THREAD

**Issue by holdsworth** [bob-anderson-ok/pymovie#5]
Hello PyMovie team,

I've been using PyMovie in my free time and I'm really impressed with the project. Great job on creating such a useful tool!

I'm wondering if there are any plans to establish community engagement channels for PyMovie users. Specifically, I'd like to know if there's a Slack channel or any other platform where users can connect, share experiences, and discuss the project.

Having a dedicated space for the community would be beneficial for:
1. User collaboration and support
2. Sharing use cases and ideas
3. Potentially contributing to the project's growth

If such a channel doesn't exist yet, would you consider creating one? I believe it would be valuable for both the users and the project's development.

Thank you for your time and consideration.

Best regards,
Holdsworth

**Comment by bob-anderson-ok** [comment]
There is a group:

***@***.***

**Comment by holdsworth** [comment]
I can't see the group ?

**Comment by bob-anderson-ok** [comment]
There’s a misspelling.

***@***.***

**Comment by holdsworth** [comment]
Please view your messages via GitHub and not through the e-mail, it doesn't render alright

**Comment by holdsworth** [comment]
Are you referring to groups io?

**Comment by bob-anderson-ok** [comment]
Yes.
